server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 60
           
spring:
  profiles: default
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:     
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true                
  thymeleaf:
    prefix: classpath:templates/
    cache: false
    suffix: .html     
  messages:
    basename: i18n/exception
    encoding: UTF-8    
    
property:
  jwt:
    secret: secret001 
  api:
    end-point: v1    
      